#!/bin/sh

/home/ajal/.arduino15/packages/MiniCore/tools/avrdude/7.1-arduino.1/bin/avrdude -C/home/ajal/.arduino15/packages/MiniCore/hardware/avr/2.2.2/avrdude.conf -v -patmega88 -carduino -P/dev/ttyUSB0 -b38400 -D -Uflash:w:$1
